#!/bin/bash
# SafeMySQLMcpServer — Interactive initialization script
# Generates .env and config/config.yaml for deployment.
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Helper functions ──

prompt() {
    local varname="$1" question="$2" default="${3:-}"
    local value
    if [ -n "$default" ]; then
        read -rp "$question [$default]: " value
        value="${value:-$default}"
    else
        read -rp "$question: " value
    fi
    eval "$varname=\"\$value\""
}

generate_secret() {
    openssl rand -base64 32 | tr -d '\n'
}

# ── Check existing config ──

if [ -f "$PROJECT_DIR/.env" ]; then
    warn "Found existing .env file."
    read -rp "Overwrite? [y/N]: " overwrite
    if [ "${overwrite,,}" != "y" ]; then
        info "Keeping existing .env. Exiting."
        exit 0
    fi
fi

if [ -f "$PROJECT_DIR/config/config.yaml" ]; then
    warn "Found existing config/config.yaml."
    read -rp "Overwrite? [y/N]: " overwrite_cfg
    OVERWRITE_CFG="${overwrite_cfg,,}"
else
    OVERWRITE_CFG="y"
fi

# ── Step 1: JWT Secret ──

echo ""
info "=== JWT Secret ==="
info "Used for API authentication. Must be at least 32 characters."
prompt JWT_SECRET "Enter JWT secret (leave empty to auto-ggenerate)" ""

if [ -z "$JWT_SECRET" ]; then
    JWT_SECRET=$(generate_secret)
    info "Auto-generated JWT secret."
fi

if [ ${#JWT_SECRET} -lt 32 ]; then
    error "JWT secret must be at least 32 characters (got ${#JWT_SECRET})."
    exit 1
fi

# ── Step 2: MySQL Connection ──

echo ""
info "=== MySQL Connection ==="
info "Enter your MySQL instance details (NOT a local dev container)."
prompt MYSQL_HOST "MySQL host" "127.0.0.1"
prompt MYSQL_PORT "MySQL port" "3306"
prompt MYSQL_USER "MySQL username" "root"
prompt MYSQL_PASSWORD "MySQL password" ""

if [ -z "$MYSQL_PASSWORD" ]; then
    error "MySQL password cannot be empty."
    exit 1
fi

prompt CLUSTER_NAME "Cluster name (identifier)" "default"

# ── Step 3: Database Mapping ──

echo ""
info "=== Database Mapping ==="
info "Enter database names to expose via MCP (comma-separated)."
info "Example: user_db,order_db"
prompt DB_NAMES "Database names" ""

if [ -z "$DB_NAMES" ]; then
    error "At least one database name is required."
    exit 1
fi

# ── Step 4: Security Config ──

echo ""
info "=== Security Config ==="
info "Security rules file path (relative to config/ directory)."
prompt SECURITY_FILE "Security rules file" "security.yaml"

# ── Generate .env ──

cat > "$PROJECT_DIR/.env" <<EOF
# SafeMySQLMcpServer environment configuration
# Generated by: make init
# Date: $(date -Iseconds)

# JWT secret (required, 32+ characters)
JWT_SECRET=${JWT_SECRET}

# Config poll interval for Docker (empty = fsnotify only, e.g. 30s)
CONFIG_POLL_INTERVAL=30s

# App port mapping
APP_PORT=8080
EOF

info "Created .env"

# ── Generate config.yaml ──

if [ "$OVERWRITE_CFG" = "y" ]; then
    # Build databases section
    DB_SECTION=""
    IFS=',' read -ra DBS <<< "$DB_NAMES"
    for db in "${DBS[@]}"; do
        db=$(echo "$db" | xargs)  # trim whitespace
        [ -n "$DB_SECTION" ] && DB_SECTION+=$'\n'
        DB_SECTION+="  ${db}:"
        DB_SECTION+=$'\n'
        DB_SECTION+="    cluster: ${CLUSTER_NAME}"
    done

    cat > "$PROJECT_DIR/config/config.yaml" <<EOF
# SafeMySQLMcpServer configuration
# Generated by: make init
# Date: $(date -Iseconds)

server:
  host: 0.0.0.0
  port: 8080

clusters:
  ${CLUSTER_NAME}:
    host: ${MYSQL_HOST}
    port: ${MYSQL_PORT}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    max_open_conns: 10
    max_idle_conns: 5
    conn_max_lifetime: 300s

databases:
${DB_SECTION}

security:
  config_file: config/${SECURITY_FILE}

audit:
  enabled: true
  log_file: logs/audit.log
  max_sql_length: 2000
  max_size_mb: 100
  max_backups: 10
  max_age_days: 30
  compress: true
EOF

    info "Created config/config.yaml"
fi

# ── Summary ──

echo ""
info "=== Setup Complete ==="
echo ""
echo "  JWT Secret:    ${JWT_SECRET:0:8}... (${#JWT_SECRET} chars)"
echo "  MySQL:         ${MYSQL_USER}@${MYSQL_HOST}:${MYSQL_PORT}"
echo "  Cluster:       ${CLUSTER_NAME}"
echo "  Databases:     ${DB_NAMES}"
echo ""
info "Next steps:"
info "  1. Review: cat .env && cat config/config.yaml"
info "  2. Deploy: make deploy"
info "  3. Generate token: make token"
